update readme example for running passed in  devnet
QuarkChain/quarkchain-web3.js pull request #21
Opened 2019-10-30 05:14 UTC by tomdong2010

networkid =0xff   in devnet   , it can be passed, this modification  can be passed

2019-10-30 05:18 UTC, ninjaahhh requested changes

2019-10-30 05:18 UTC, ninjaahhh commented on README.md
> +var contractInstance = MyContract.new([constructorParam1] [, constructorParam2], {data: '0x12345...', from: myAccount, gas: 1000000,gasPrice:1000000000,fromFullShardKey:fromFullShardKey,toFullShardKe
add spaces between fields

2019-10-30 05:18 UTC, ninjaahhh commented on index.js
> +//
remove

2019-10-30 05:18 UTC, ninjaahhh commented on index.js
> +          //
remove

2019-10-30 05:18 UTC, ninjaahhh commented on index.js
> +
remove extra space

2019-10-30 05:18 UTC, ninjaahhh commented on index.js
> +
remove extra space

2019-10-30 05:18 UTC, ninjaahhh commented on index.js
> +
same

2019-10-30 05:18 UTC, ninjaahhh commented on index.js
> +
same

2019-10-30 06:10 UTC, tomdong2010 commented on index.js
> +
ok

2019-10-30 06:12 UTC, tomdong2010 commented on README.md
> +var contractInstance = MyContract.new([constructorParam1] [, constructorParam2], {data: '0x12345...', from: myAccount, gas: 1000000,gasPrice:1000000000,fromFullShardKey:fromFullShardKey,toFullShardKe
ok

2019-10-30 18:19 UTC, ninjaahhh commented on README.md
> +var contractInstance = MyContract.new([constructorParam1] [, constructorParam2], {data: '0x12345...', from: myAccount, gas: 1000000,gasPrice: 1000000000,fromFullShardKey: fromFullShardKey, toFullShar
add a space between `gas` and `gasPrice`, also the other fields

2019-11-11 19:17 UTC, ninjaahhh approved these changes

2019-11-12 01:15 UTC, merged